name: Check, test and format the Rust part of codebase

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  actions: write
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash
    working-directory: src-tauri

jobs:
  pake-build:
    name: Test codebase on ${{ matrix.os }} (cargo test)
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - windows-latest
          - ubuntu-latest
          - macos-latest
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - uses: rui314/setup-mold@v1
      - uses: taiki-e/install-action@v1
        with:
          tool: cargo-hack,nextest
      - name: Install dependencies for Ubuntu
        if: matrix.os == 'ubuntu-latest'
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: >
            libwebkit2gtk-4.0-dev build-essential curl wget libssl-dev
            libgtk-3-dev libayatana-appindicator3-dev librsvg2-dev
          version: 1.0
      - name: build windows
        if: matrix.platform == 'ubuntu-latest'
        run: |
          npm run build:linux_all
      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'windows-latest'
        run: |
          npm run build:windows_all
